<?php

namespace Mintdev\Xml\Logger\Types;

enum Step: string
{
    case FROM_CALLER_TO_SERVICE = "FROM_CALLER_TO_SERVICE";
    case FROM_SERVICE_TO_CALLER = "FROM_SERVICE_TO_CALLER";
    case FROM_SERVICE_TO_BACKEND = "FROM_SERVICE_TO_BACKEND";
    case FROM_BACKEND_TO_SERVICE = "FROM_BACKEND_TO_SERVICE";
}